### ISSUE TITLE
unable to copy/paste text in iTerm2/Mac

### ISSUE THREAD

**Issue by lakamsani** [johndgiese/dotvim#3]
Hi, thanks for sharing your setup. It all works well except that I seem to have lost the ability to copy/paste highlighted text from a file open in vim with this setup. Any thoughts on how to get that going?

**Comment by johndgiese** [comment]
Hmm strange---I also use iterm2, and I can copy/paste just fine.  Try opening vim using `vim -u NONE` and see if you can copy paste then.

**Comment by lakamsani** [comment]
Hi, I 'm able to copy/paste using vim -u NONE. I attached a couple of screen shots first is with your setup and the second is with -u NONE

<img width="1168" alt="vim-with-johndgiese-setup" src="https://cloud.githubusercontent.com/assets/3322496/15802096/18f7272c-2a5d-11e6-89b5-2ec97fbbe0f1.png">
<img width="690" alt="vim-vanilla" src="https://cloud.githubusercontent.com/assets/3322496/15802095/18f6ec30-2a5d-11e6-98f6-f0038cd67e35.png">

**Comment by johndgiese** [comment]
I see.  Ok, so I have been doing this so long it is just part of my finger memory.  Hold ALT when you select to force term to handle the selection.  Otherwise, vim (with my setup) will intercept the key presses and interpret it as "visual mode selection".

You can turn this off by changing this line:

https://github.com/johndgiese/dotvim/blob/master/vimrc#L19

from `set mouse=a` to `set mouse=''`.

See the vim help file for "mouse".

**Comment by lakamsani** [comment]
That works. Thank you for your quick response.
